qlik-oss/picasso.js

- docs/package-lock.json
- docs/package.json
enforce marked@^0.3.9 in package.json in docs
> chore: enforce marked@^0.3.9 for security reasons

- website/static/css/custom.css
Logo "stays" behind and you only scroll the main page when you go up, like a... curtain? 
Almost like a parallax effect :)
> docs: Website static scroll effect

- docs/dist/plugin-q.md
- docs/src/input/plugin-q.md
- plugins/q/README.md
> docs: fix typos in plugin-q

- .circleci/config.yml
- packages/picasso.js/package-lock.json
- packages/picasso.js/package.json
- plugins/hammer/package-lock.json
- plugins/hammer/package.json
`persist_to_workspace` and `restore_cache` command don't handle symlinked packages (the private packages), so had to resort to `bootstrap`ing on each job to recreate the the symlink.
> chore: update ref to private packages

- website/pages/en/examples.js
Adds two new categories on the example page `Brushing` and `Miscellaneous`.  As the API for thumbnails has changed and is currently not working as expected on Observable, the thumbnail for `Create your own component` example is empty.
> docs: add brushing and misc examples

- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/test/unit/core/component/component-factory.spec.js
BREAKING CHANGE
getAffectedShapes no longer returns each matching shape multiple times for each trigger in the related component.
Also changed (breaking) so that a affected shape is defined by the consume configuration instead of the trigger config.
```js
// Before
{
trigger: [{
contexts: ['test']
}]
}
// After
{
consume: [{
context: 'test'
}]
}
```
**Checklist**
> fix: getAffectedShapes should not return duplicates

- packages/picasso.js/src/core/scales/band.js
- packages/picasso.js/test/unit/core/scales/band.spec.js
Fixes band scale's `.datum()` method, which probably degraded during refactoring
> fix: band scale datum method returns undefined

- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/picasso.js/test/unit/web/renderer/canvas-renderer/canvas-renderer.spec.js
- packages/picasso.js/test/unit/web/renderer/svg-renderer/svg-renderer.spec.js
This fixes an issue where rendering did not occur after a clear due the scene being the same.
**Checklist**
> fix(renderer): reset scene when clearing render

- .eslintignore
- package-lock.json
- package.json
- packages/path2d-polyfill/package.json
- packages/picasso.js/package-lock.json
- packages/picasso.js/package.json
- packages/picasso.js/test/integration/chart/brushing/over.fix.html
- packages/picasso.js/test/integration/chart/brushing/tap.fix.html
- packages/picasso.js/test/integration/chart/brushing/tap_scroll.fix.html
- packages/picasso.js/test/integration/plugins/hammer.fix.html
- plugins/hammer/package.json
- plugins/q/package.json
- rollup.config.js
* Sourcemaps are now always built
* Only one file is outputted instead of two, `dist/picasso.js` (this is minifed on build, but still mapped to the sourcemap)
* Introduced rollup-plugin-clean for `dist` folder so the .min. file does not keep laying around
* On watch it skips uglifying to build faster
* `npm run build:dev` removed
> chore: Simplify rollup

- .circleci/config.yml
- packages/picasso.js/src/core/chart-components/legend-seq/legend-seq.js
- packages/picasso.js/src/core/chart-components/legend-seq/node-builder.js
- packages/picasso.js/test/unit/core/chart-components/legend-seq/legend-seq.spec.js
Introduced fallback to title from majorScale data in legend-seq similar to how legend-cat works
> fix(legend-seq): Title use fallback from majorScale

- packages/picasso.js/src/core/component/brushing.js
- packages/picasso.js/test/unit/core/component/brushing.spec.js
Changes the behavior for the default brush start listener. Now all shapes becomes inactive by default.
```js
chart.brush('myContext').start(); // will now inactive all shapes and trigger their consume action.
```
**Checklist**
> fix: inactive all shapes on brush start

- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/test/unit/core/chart-components/legend-cat/legend-resolver.spec.js
If the categorical scale for the `legend-cat` component have a discrepancy between the data mapping and its domain, ex. the domain is ordered differently or contains a different number of items. The `legend-cat` would base the datum `value` from the data and the datum `label` from the domain. 
This fix ensures that both value and label use the domain to resolve a proper datum.
**Checklist**
>  fix: possible mismatch between value/label in legend-cat

- docs/dist/data.md
- docs/src/input/data.md
- packages/picasso.js/src/core/data/extractor.js
- packages/picasso.js/test/unit/core/data/extractor.spec.js
Add support for sorting extracted data items by adding a `sort`
option to the `data` config
Solves #50
**Checklist**
> feat: sort extracted data

- packages/picasso.js/src/core/chart-components/pie/pie.js
- packages/picasso.js/test/unit/core/chart-components/pie.spec.js
Adds a share value (0-1) on each slice. Also added a filter to remove any data value that is negative or NaN, previously all those values where passed to the renderer but didn't have any size/area.
This change exposes a way to show share percentage in for example labels and tooltip.
**Checklist**
> feat: share per slice

- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/picasso.js/test/unit/core/component/component-factory.spec.js
There was a inconsistency in which some methods exposed meta data on the scene node. Now all APIs that return a collection of scene nodes, contains the key (given the component has a key) and element property.
This affects the following methods:
- `chartInstance.findShapes`
- `chartInstance.shapesAt`
- `chartInstance.getBrushedShapes`
**Checklist**
> fix(scene-node): append all component meta

- docs/spec.json
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
- packages/picasso.js/src/core/chart-components/labels/strategies/rows.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/bars.spec.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/rows.spec.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/slices.spec.js
This PR adds a new property on the label component called `linkData`. Linking data on the label node allows the labels to be used in brushing.
The property is optional and off by default.
**Checklist**
>  feat(labels): link data on label

- packages/picasso.js/src/core/scene-graph/display-objects/circle.js
- packages/picasso.js/src/core/scene-graph/display-objects/display-object.js
- packages/picasso.js/src/core/scene-graph/display-objects/rect.js
- packages/picasso.js/src/core/scene-graph/display-objects/text.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/picasso.js/src/web/text-manipulation/inject-textbounds.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/text.spec.js
This PR changes the default behavior of text nodes, they will now have a collider attached by default given that they are data bound. This enables text nodes to be targeted by interactions (brushing and shape look-up).
There is a performance impact here when the text is measured and the collider is created. It would be good to have colliders lazy evaluated (for all type of nodes) to reduce the overhead of enabling interactions. But I consider that out-of-scope for this PR.
> feat(scenegraph): add default collider on text nodes

- packages/picasso.js/src/core/scene-graph/collision-resolver.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/text.spec.js
Fixes an issue where bounds collisions would not be resolved properly on nodes with a transform.
> fix(scene-graph): bounds collision

- packages/picasso.js/src/core/charts/chart.js
- packages/picasso.js/test/component/chart/chart.comp.js
Before new components was rendered before old
**Checklist**
> fix(render-order): Render components in specified order

- plugins/q/src/brush/q-brush.js
- plugins/q/test/unit/q-brush.spec.js
Fixes an issue when calculating the appropriate measure index to use for an attribute expression, and layout is missing.
**Checklist**
> fix(q): fix q brush when layout is missing

- plugins/q/src/brush/q-brush.js
- plugins/q/test/unit/q-brush.spec.js
**Checklist**
Handle qNoOfLeftDims = -1, specifically selecting in the left dimension. Documentation here: https://help.qlik.com/en-US/sense-developer/June2018/apis/EngineAPI/definitions-HyperCubeDef.html
> fix(q): handle qNoOfLeftDims = -1 for q-brush

- plugins/q/test/unit/scales/qTime/tick-generator.spec.js
There seems to be a Node issue that causes these tests to fail on MacOSx. Disable until issue is resolved.
> test: disable failing test

- packages/picasso.js/package.json
Publish source files so that `"module": "src/index.js"` works when transpiling picasso files as a npm dependency.
> chore: publish source files

- packages/picasso.js/src/core/scene-graph/collision-resolver.js
- packages/picasso.js/src/core/scene-graph/display-objects/circle.js
- packages/picasso.js/src/core/scene-graph/display-objects/container.js
- packages/picasso.js/src/core/scene-graph/display-objects/display-object.js
- packages/picasso.js/src/core/scene-graph/display-objects/line.js
- packages/picasso.js/src/core/scene-graph/display-objects/path.js
- packages/picasso.js/src/core/scene-graph/display-objects/rect.js
- packages/picasso.js/src/core/scene-graph/display-objects/text.js
- packages/picasso.js/src/core/scene-graph/scene-node.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/circle.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/container.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/display-object.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/gradient-item.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/line.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/path.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/rect.spec.js
- packages/picasso.js/test/unit/core/scene-graph/display-objects/text.spec.js
This fixes an issue where a container with a bounds collider would not resolve transform on it's children properly when doing collision test. It was mostly notable on the `box` component, where brushing/shapesAt would not work properly on HiDPI devices (MacBook/mobile devices).
The issue was introduced as a part of #115 and exposed from picasso.js ^0.10.0.
The actual solution resolves the node collider function upon first use, instead of while the node is created. This allow the transform on all node to be resolved before it's used.
> fix(scene-graph): bounds collision with transform

- docs/src/input/brushing.md
- packages/picasso.js/src/core/component/brushing.js
- packages/picasso.js/test/unit/core/component/brushing.spec.js
This PR adds support for filtering shapes when consuming a brush:
```js
{
brush: {
consume: [{
context: 'highlight',
filter: s => s.fill === 'red', // apply only on red shapes
style: {
inactive: {
opacity: 0.3
}
}
}]
}
}
```
**Checklist**
> feat: add filter for brush consumer

- packages/picasso.js/src/core/chart-components/box/__tests__/box-shapes.spec.js
- packages/picasso.js/src/core/chart-components/box/box-shapes.js
The `minWidthPx` setting for the box component was accidentally removed. This PR adds support for it again.
> fix(box): add logic for minWidthPx

- packages/picasso.js/src/web/components/brush-range/__tests__/brush-area-dir.spec.js
- packages/picasso.js/src/web/components/brush-range/__tests__/brush-range.spec.js
- packages/picasso.js/src/web/components/brush-range/brush-area-dir.js
- packages/picasso.js/src/web/components/brush-range/brush-range-node-builder.js
- packages/picasso.js/src/web/components/brush-range/brush-range.js
Add keys to dom elements in the form of data attributes in order to identify the elements during event handling.
> feat(range-brush): add keys to dom elements

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
Adds support for sorting layers:
```js
settings: {
coordinates: {
minor: { scale: 'y' },
major: { scale: 'x' },
layerId: { ref: 'year' } 
},
orientation: 'horizontal',
layers: {
sort(a, b) { return b.data[0].minor.value - a.data[0].minor.value; } // sort by first point in descending order
line: {
strokeWidth: 2,
stroke: 'red'
},
}
}
```
closes #220
> feat(line): add layer sort option

- packages/picasso.js/src/core/dock-layout/dock-layout.js
- packages/picasso.js/test/component/chart/chart.comp.js
The JavaScript sort algorithm implementation does not guarantee object order when sorting on object properties:
> If `compareFunction(a, b)` returns `0`, leave `a` and `b` unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAscript standard does not guarantee this behaviour, and thus not all browsers (e.g. Mozilla versions dating back to at least 2003) respect this. Read more: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description
This was causing issues in a project I'm working on, specifically in Chrome.
This PR adds a check if the displayOrder is equal, and if so, uses the original array index to preserve the order.
The output below is based on 11 components, all defined _without_ setting …
> fix(layers): preserve original index if equal

- packages/picasso.js/src/core/chart-components/axis/axis-label-size.js
- packages/picasso.js/src/core/chart-components/axis/axis.js
Fix an issue where labels and ticks would be renderer outside the normal axis area.
> fix(axis): labels rendered outside the axis area

- docs/scriptappy.json
- packages/picasso.js/src/core/scene-graph/__tests__/scene-node.spec.js
- packages/picasso.js/src/core/scene-graph/scene-node.js
This adds the ability to get parent and child nodes from a scene node. Which enables basic traversing of the scene graph.
All API:s that returns a scene node are affected.
```js
chartInstance.findShapes('container')[0].children.forEach(child => {
// Do something with the child node
});
```
> feat(scene-graph): get parent and child nodes

- packages/picasso.js/src/core/data/__tests__/dataset.spec.js
- packages/picasso.js/src/core/data/data.js
- packages/picasso.js/src/core/data/dataset.js
Fixes an issue where the dataset source was not pass down correctly to the field. Resulting in wrong field identifier.
A unfortunate side-effects of this issue was that brushing would not be applied properly in some cases.
```js
// Before
chartInstance.dataset('Producs').field('Sales').id() // would output `undefined/Sales`
// After
chartInstance.dataset('Producs').field('Sales').id() // will output `Products/Sales`
```
> fix(data): undefined data source in field

- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/index.js
Makes it possible to send in an array called `excludeFromUpdate` in which you can specify the keys of the components you want to exclude from updating. This array is to be passed into `chartInstance.update`. This is one approach of optimizing performance (only re-render/update what's actually changed).
> feat: make it possible to exclude specific components from update

- packages/picasso.js/src/core/chart-components/box/__tests__/box-shapes.spec.js
- packages/picasso.js/src/core/chart-components/box/box-shapes.js
The out of bounds arrow symbol was in the right place, but when specifying flipXY it did not take arrow direction into account. This is now fixed and added proper tests for it aswel..
**Checklist**
> fix(box): out of bounds symbol arrow direction

- package.json
- yarn.lock
Revert rollup version to `0.66.2` due to invalid source-map generation in versions since `0.66.3`. 
https://github.com/rollup/rollup/issues/2525
> chore: fix source-map generation

- packages/picasso.js/src/core/chart-components/debug/debug-collider.js
- packages/picasso.js/src/core/chart-components/debug/debug-path-to-points.js
Some components, like the axis for example, use the outer dock area as its container, causing issues when trying to dock on top of the component. This enable one to force the use of the outer dock area via a setting.
> feat(debug): add support for components that use the outer area

- packages/picasso.js/src/web/components/tooltip/__tests__/placement.spec.js
- packages/picasso.js/src/web/components/tooltip/placement.js
Given a shape was only partially visible, the tooltip could in some scenarios be on the non-visible part of the shape. This PR clamps the tooltip position to the visible part.
> fix(tooltip): clamp position to component bounds

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-node-builder.spec.js
- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-size-calculator.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis-default-settings.js
- packages/picasso.js/src/core/chart-components/axis/axis-label-size.js
- packages/picasso.js/src/core/chart-components/axis/axis-node-builder.js
This PR adds the ability configure how the axis should behave when labels are overlapping. The default behavior is the same as before.
To toggle on filter:
```js
{
// Toggle whether labels should be filtered if they are overlapping. Filtering may be applied in a non-sequential order. If labels are overlapping and this setting is toggled off, the axis will automatically hide
settings: { labels: { filterOverlapping: true } }
}
```
There are some improvements that could be made on how it behaves in certain scenarios. Especially when the axis direction and labels are horizontal. But that would require a rather major change to the underlying axis code to fix. So it will have to wait for now.
> feat(axis): add filter overlapping labels setting

- packages/picasso.js/src/core/chart-components/box/__tests__/box-shapes.spec.js
- packages/picasso.js/src/core/chart-components/box/box-shapes.js
Fixes an issue where `minWidthPx` and `maxWidthPx` settings didn't work when the major scale was inverted.
> fix(box): min/maxWidthPx doesnt work when scale is inverted

- packages/picasso.js/src/core/dock-layout/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/dock-layout/dock-layout.js
**Checklist**
Updates the visible and hidden components based on components that are docked to other components.
For example, assume a component called myRect:
{
key: 'myRect',
type: 'rect',
dock: 'bottom'
}
and a component called myLine:
{
key: 'myLine',
type: 'line',
dock: '@myRect'
}
if the layout engine decides to hide myRect, then myLine should be hidden as well.
> fix(dock-layout): remove components that are docked at hidden components

- docs/scriptappy.json
- docs/src/input/component-brush-area-dir.md
- packages/picasso.js/src/web/components/brush-range/brush-area-dir.js
Adds support for multiple fill targets:
```js
{
target: {
components: ['a', 'b']
}
}
```
> feat(brush-area-dir): add support for multiple fill targets

- packages/picasso.js/src/web/components/brush-range/brush-area-dir.js
Remove brush targets that do not have a `rect` property
> fix(brush-area-dir): remove targets without rect

- plugins/q/src/data/extractor-t.js
When qDataPages was empty an exception was thrown. This handles that case a by adding a first or default check.
> fix(q): add first or default check for empty qDataPages in extractor-t

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/formatter/__tests__/formatter.spec.js
- packages/picasso.js/src/core/chart/formatter/index.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/chart/scales/__tests__/scales.spec.js
- packages/picasso.js/src/core/chart/scales/index.js
Changes so that scales and formatters are evaluated when they are requested, instead of during chart creation. This improves performance as data extraction for unused scales/formatters will not be performed.
**Checklist**
> perf: lazy evaluation of scales and formatters

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars-overlapping-filter.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars-overlapping-filter.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
This PR adds a new property on the labels components `bar` strategy. Enabling texts to be rendered even when they don't fully fit the bar.
There is a performance overhead introduced each label needs to be checked for possible intersections with other nodes and when all selected bars are sorted by direction.
The logic for determining the best possible placement doesn't consider overflow property for now.
Also should rename it to something other than overflow..
**Usage:**
```js
{
type: 'labels',
settings: {
sources: [
{
component: 'bars',
selector: 'rect',
strategy: {
type: 'bar',
settings: {
labels: [{
placements: [
{ position: 'outside', fill: '#666', overflow: true }
]
}]
}
},
},
],
},
}
```
**Checklist**
> feat(labels): allow text to overflow bars

- packages/picasso.js/src/core/scene-graph/display-objects/circle.js
- packages/picasso.js/src/core/scene-graph/display-objects/container.js
- packages/picasso.js/src/core/scene-graph/display-objects/line.js
- packages/picasso.js/src/core/scene-graph/display-objects/path.js
- packages/picasso.js/src/core/scene-graph/display-objects/rect.js
- packages/picasso.js/src/core/scene-graph/display-objects/text.js
This improves performance for calculating the bounding rectangle of a node. All calculations are now cached either with a transformation applied or without.
**Checklist**
> perf: cache bounds calculations

- plugins/q/src/formatter/timeFormat.js
> perf(q): memoize time formatter

- docs/src/input/brushing.md
- packages/picasso.js/src/core/component/__tests__/brushing.spec.js
- packages/picasso.js/src/core/component/brushing.js
This exposes `mode` on the brush consumer, allowing the user to set a condition on the data properties that need to be fulfilled in order to be considered brushed.
By default, a data item is considered brushed if data linked to any of the provided `data` properties is brushed.
By providing a `mode: 'and'`, we set a condition so that an item is considered brushed only of all its linked properties are brushed:
```js
consume: [{
context: 'selection',
data: ['x', 'y'],
mode: 'and', // valid values: 'and', 'xor', 'or' (default)
style: {
active: {
fill: 'red',
},
}
}]
```
> feat: expose mode on brush consumer

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
Fixes `justify` in bar labeling strategy when bar `direction` is `'left'`
Before:
After:
> fix: invert justify when bar direction is left

- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-renderer.spec.js
- packages/picasso.js/src/web/renderer/dom-renderer/__tests__/dom-renderer.spec.js
- packages/picasso.js/src/web/renderer/index.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-renderer.spec.js
Sets a `data-key` attribute on all component container elements. I would primarily consider this a debug aid when inspecting elements.
> feat: set component key as attribute on renderer element

- packages/picasso.js/src/core/component/__tests__/component-factory.spec.js
- packages/picasso.js/src/core/component/component-factory.js
**Checklist**
- instantiate all components with empty emit functions if they don't already have defined emitters.
> fix: setup emits on all components

- docs/src/input/plugin-q.md
- plugins/q/src/data/__tests__/dataset.spec.js
- plugins/q/src/data/__tests__/extractor-s.spec.js
- plugins/q/src/data/__tests__/extractor-t.spec.js
- plugins/q/src/data/dataset.js
- plugins/q/src/data/extractor-s.js
- plugins/q/src/data/extractor-t.js
- plugins/q/src/data/field.js
Adds experimental support for virtual fields:
```js
const ds = picasso.data('q')({
key: 'qHyperCube',
data: layout.qHyperCube,
config: {
virtualFields: [{
key: 'surpriseMe',
from: 'qMeasureInfo/0',
override: {
value: v => v.qValue * Math.random(),
}
}]
}
});
ds.field('surpriseMe').items(); // -> array of random numbers multiplied with the value from first measure
```
> feat(q): add experimental virtual fields

- docs/src/input/components.md
- packages/picasso.js/src/core/component/__tests__/component-factory.spec.js
- packages/picasso.js/src/core/component/component-factory.js
**Checklist**
- allows a user to get the visibility of a component after it has been rendered.
> feat: expose the visibility of a component

- packages/picasso.js/src/core/scene-graph/display-objects/text.js
Fixes `title='undefined'` in DOM output
Before:
```html
<text title="undefined" data-value="0" data-label="Americas">Americas</text>
```
After:
```html
<text data-value="0" data-label="Americas">Americas</text>
```
> fix(svg-renderer): do not add undefined title attribute

- docs/scriptappy.json
- packages/picasso.js/src/core/scene-graph/__tests__/scene-node.spec.js
- packages/picasso.js/src/core/scene-graph/scene-node.js
Exposes a new method on the SceneNode that can be used to retrieve the bounding rectangle of the SceneNode relative to some target. Where the target may be a HTMLElement or the browser viewport.
**Usage**
```js
node.boundsRelativeTo($('div'));
node.boundsRelativeTo('viewport');
```
> feat(scene-node): add boundsRelativeTo method

- packages/picasso.js/src/core/chart-components/labels/strategies/bars-overlapping-filter.js
When a label is created through approxTextBounds function in bars.js, we add a padding 8 pixels to the width and the height which can make the label is not fully inside the container. This happens when a label is at the top of a bar and it is not shown up because it is not fully inside the container. What we need to check is if the label is fully inside the container only in the orientation of the chart.
> fix(label): take orientation into account when checking label visibility

- packages/picasso.js/src/core/chart-components/legend-cat/legend-cat.js
- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/dock-layout/dock-layout.js
- packages/test-utils/mocks/element-mock.js
This makes sure components that have manually injected elements are tracked and ordered according to component order.
**Checklist**
> fix: keep track of element order

- packages/picasso.js/src/core/component/component-factory.js
This solves an issue when `preferredSize` has been updated in a component definition but the component keeps using the `preferredSize` specified in the initial definition.
This solution updated the config object in the `component-factory` when a component is updated. It might not be the optimal solution, or it may have unexpected effects... What do you guys think, @miralemd, @cbt1 ?
> fix: update component config

- packages/picasso.js/src/web/components/brush-range/__tests__/brush-area-dir.spec.js
- packages/picasso.js/src/web/components/brush-range/brush-range-node-builder.js
Fixes issue where range edges weren't being rendered if dragging in negative direction.
**Checklist**
> fix(brush-area-dir): render negative ranges

- packages/picasso.js/src/web/components/brush-range/brush-range-node-builder.js
Fixes minor issue where edges weren't rendered if edge value was outside min/max due to floating point calculation.
> fix(brush-range): handle floating point

- packages/picasso.js/src/core/chart-components/grid/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/grid/line.js
use settings-resolver
ex:
ticks: {
show: (t, ix) => ix % 2 == 0, // show every other line
stroke: t => t.data.dir === 'x' ? 'red' : 'blue' // color depending on direction
},
**Checklist**
> feat(grid-lines): support callbacks in grid-line settings

- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/text.js
Changing canvas state is expensive. This PR attempts to reduce the number of changes required by checking new value vs current value.
The `dir` is not stored on canvas context and as such not stored when `save()` method is called, the value should under normal circumstance not change after the initial set.
`textAlign` is however stored by calling `save()`. This should mean that it's only applicable if the value is equal to the default value "start".
> perf(canvas-renderer): set text context only when needed

- plugins/q/src/data/extractor-t.js
**Checklist**
- By switching for each loops to regular for loops inside extractor-t.js the following results was yielded when running performance benchmarks. This was tested on around 500 field values.
Extraction on qDimensionInfo/0
for each loops
~2700 ops/s
for loops
~ 4851 ops/s
Extraction on qDimensionInfo/1
for each loops
~1697 ops/s
for loops
~ 3000 ops/s
- In order to check out the metrics, please check out the branch located on this link and follow the instructions in README.md https://github.com/nguyenlam1/picasso.js/tree/perf-extract-t/plugins/q/src/data
> perf(q): switch for each loops to for loops in extractor-t

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-size-calculator.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis-default-settings.js
- packages/picasso.js/src/core/chart-components/axis/axis-label-size.js
**Checklist**
- Gives the user the ability to set the tilt threshold of axis labels.
Usage 
```js
// Inside the axis component
{
type: 'axis',
scale: 'myDiscreteScale',
dock: 'bottom'
settings: {
labels: {
mode: 'auto',
tiltThreshold: 0.9 // Toggle on tilt, if less than 90% of the labels are visible
}
}
}
```
> feat(axis): add tiltThreshold

- packages/picasso.js/src/web/components/tooltip/__tests__/tooltip.spec.js
- packages/picasso.js/src/web/components/tooltip/tooltip.js
Fixes an issue where the tooltip would become really small if the chart was scaled down. This changes so that the tooltip root element will be the same size as the appendTo element.
> fix(tooltip): scaling when using appendTo

- packages/picasso.js/src/core/chart/index.js
IE11 throws "Unspecified error" when trying to insert an element before itself when it has the property `_reactRootContainer` (which contains DOM references).
> fix: only move elements that have new position

- packages/picasso.js/src/core/dock-layout/dock-settings-resolver.js
Ceiling lead to components using more space than available in certain scenarios.
> fix(dock-layout): floor instead of ceil when rounding container values

- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-label-node.spec.js
- packages/picasso.js/src/core/chart-components/axis/__tests__/get-continuous-label-rect.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis-label-node.js
- packages/picasso.js/src/core/chart-components/axis/axis-node-builder.js
- packages/picasso.js/src/core/chart-components/axis/get-continuous-label-rect.js
Aims to fix an issue where a continuous horizontal axis would be far too strict in the amount of space available for labels to render. 
Also fixes an issue where labels at the ends would be partially clipped.
Before - All ticks share the same amount of possible space to occupy and the spacing scales with the size of the chart.
After - The space for each tick is calculated individually and uses static padding between them.
> fix(axis): ellipsis threshold for continuous horizontal axis

- packages/picasso.js/src/web/components/brush-range/__tests__/brush-range.spec.js
- packages/picasso.js/src/web/components/brush-range/brush-range.js
Fixes so that `range-brush` only renders nodes from an observed brush or when the brushing occurred from the component itself.
This is to avoid the component rendering nodes from brushes that were activated by other components.
> fix(range-brush): only render nodes from observed or active brush

- plugins/q/src/formatter/__tests__/timeFormat.spec.js
- plugins/q/src/formatter/parts/qs-date-formatter.js
- plugins/q/src/formatter/timeFormat.js
Fixes an issue where some date values would return wrong formatted value.
**Checklist**
> fix(q-time-format): floating point precision

- docs/scriptappy.json
- docs/src/input/component-brush-range.md
- packages/picasso.js/src/web/components/brush-range/brush-range.js
Match the functionality of brush-area-dir added in #266 
Adds support for multiple fill targets:
```
{
target: {
components: ['a', 'b']
}
}
```
> feat(brush-range): add support for multiple fill targets

- packages/picasso.js/src/core/scene-graph/display-objects/rect.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/__tests__/rect.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/rect.js
Adds support for rounded rectangle in the scene graph and svg/cavans renderer.
Usage:
```js
{ type: 'rect', rx: 10, ry: 5 }
```
There are a couple instance where the svg and canvas output may be different:
- There is a known implementation limitation that affects the canvas renderer. The method used to approximate a rounded rectangle is not precise enough when the radius approaches half the width or height.
- When using the svg renderer, chrome v73 doesn't handle the case when either the rx or ry property is missing.
> feat(renderer): rounded rectangle

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
This PR includes:
1. adding padding for bar labels which is used to calculate the label bound and check if the label bound is fit a bar or not,
2. adding background color to the label which is useful in case of showing stack total values when they are rendered inside bar segments.
> fix(bar-label): add padding and background color to bar labels

- docs/scriptappy.json
- docs/src/input/chart.md
- docs/src/input/dock-layout.md
- packages/picasso.js/src/core/chart/index.js
BREAKING CHANGE: rect is now a reserved keyword for components
A lot of examples used the `beforeRender` lifecycle method to set `this.rect` on the component:
```js
beforeRender(opts) {	
this.rect = opts.size;	
},
```
💥 **`rect` is now a reserved keyword and automatically set on all components by the layout strategy**. Trying to assign a value to `rect` inside a component will throw an error.
> The actual breaking PR is https://github.com/qlik-oss/picasso.js/pull/354, but it did not contain any BREAKING CHANGE comment, so adding it in this commit instead.
Properties related to the layout strategy have been moved one step down into a `layout` object, while `dockLayout` has been renamed to `strategy`:
**Before**
```js
picasso.chart({
settings: {
dockLayout: { // deprecated, use strategy …
```
> docs: update dockLayout references

- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/core/layout/dock/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/layout/dock/docker.js
in PR #354 we prepared for the compose api where we were thinking to rename the `preferredSize` method in components to `getPreferredSize` but there is no need to break this api. This PR reverts the change.
**Checklist**
> refactor: keep preferredSize api

- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/layout/dock/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/layout/dock/docker.js
- packages/picasso.js/src/web/components/tooltip/__tests__/tooltip.spec.js
- packages/picasso.js/test/helpers/component-factory-fixture.js
Fixes so that elements in the DOM are ordered according to `displayOrder`.
> fix(layout): maintain display-order

- packages/picasso.js/src/core/utils/__tests__/registry.spec.js
- packages/picasso.js/src/core/utils/registry.js
- packages/picasso.js/src/index.js
When accessing registries with a wrongful key we're now logging a warning.
**Checklist**
> feat: log warning for unintentional registry use

- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/core/layout/dock/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/layout/dock/docker.js
in #354 we introduced that component definition can access the settings provided by the user with `this.userSettings`. This reverts the change
**Checklist**
> refactor: revert userSettings

- packages/picasso.js/src/core/layout/dock/config.js
- packages/picasso.js/src/core/layout/dock/docker.js
- packages/picasso.js/test/helpers/component-factory-fixture.js
in the compose API the dock layout goes straight to the components to ask for preferredSize (not via the dock config object).  This PR makes is a preparation for that.
**Checklist**
- [x ] commits conform to the [commit guidelines](./CONTRIBUTING.md#commit)
> refactor: correct call for preferredSize in dock layout

- packages/picasso.js/src/core/component/component-factory.js
Fixes an issue where computedInner and computerOuter rect would be undefined if a component was hidden by the dock layout. Causing a cascade of outer issues when components would expect them to be available.
> fix: computedInner and computerOuter rect is undefined

- packages/picasso.js/src/core/layout/dock/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/layout/dock/docker.js
If the rect for the dock-layout was not originating from x:0 y:0 the laid out components got wrongly positioned as if they were originating from x:0 y:0
**Checklist**
> feat: dock layout for rects not in origin

- packages/picasso.js/src/web/text-manipulation/__tests__/text-metrics.spec.js
- packages/picasso.js/src/web/text-manipulation/text-metrics.js
This PR aims to improve the performance of the measure text function for a specific use case, that is when multiple calls to measure text function share the same font size and font family, which is typically the case when the ellipsis function iterates over some text to find a suitable break point.
As always with these kinds of micro-optimisations it's hard to determine the impact. But in one case when never hitting the cache and using same font styling - latest chrome version seem to yield up to 30% better performance. In most of other cases it appears to stay more or less the same.
> perf: text metrics

- packages/picasso.js/src/core/chart-components/legend-cat/title-renderer.js
Fixes an issue where the title could clip the top of certain characters.
> fix(legend-cat): title baseline

- plugins/q/src/brush/__tests__/q-brush.spec.js
- plugins/q/src/brush/q-brush.js
**Checklist**
- Switch the selection call to selectPivotCell for ```qMode: 'K'```
> fix(q): handle qMode: 'K' in q-brush

- packages/picasso.js/src/web/text-manipulation/__tests__/font-size-to-height.spec.js
- packages/picasso.js/src/web/text-manipulation/__tests__/text-metrics.spec.js
- packages/picasso.js/src/web/text-manipulation/font-size-to-height.js
- packages/picasso.js/src/web/text-manipulation/text-metrics.js
Changes how the height of a text is measured to a method based on the font-size pixel value. This will make it less prone to issue with fonts that have narrow style for the character `M`.
See example below using `Arial` for the difference when computing the bounding rectangle of a text. Where the red rectangle is the bounds.
**Before**
**After**
> fix(text-metrics): height measurement

- packages/picasso.js/src/core/chart-components/legend-cat/__tests__/item-renderer.spec.js
- packages/picasso.js/src/core/chart-components/legend-cat/item-renderer.js
Problem:
When legend scroll offset is set before the data is set, the legend scroll offset will be reset to zero after the data is set (through getItemsToRender).
The problem comes from the fact that after the offset is set to zero, it is never reinitialized again by the checking offset === null in itemize function.
Solution:
Remove checking offset === null in the itemize function.
This will fix the problem of legend scroll offset is always at zero in the snapshot mode when a bar chart has 2 dimensions.
Before this fix:
After this fix:
> fix(legend-cat): fix setting initial legend scroll offset

- packages/picasso.js/src/web/text-manipulation/__tests__/text-metrics.spec.js
- packages/picasso.js/src/web/text-manipulation/line-break-resolver.js
- packages/picasso.js/src/web/text-manipulation/text-metrics.js
Fixes an issue where the condition for computing the text node bounds was not always the same as the condition for the rendering logic. Such that the bounds may be computed based on line breaking while the rendered text would not be.
> fix(text-metrics): condition for using line break when computing bounds

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/src/core/chart-components/legend-cat/navigation-renderer.js
This PR is to allow disabling navigation buttons of a categorical color legend.
> fix(legend-cat): add enabled/disabled state to navigation buttons

- packages/picasso.js/src/core/chart-components/legend-cat/__tests__/item-renderer.spec.js
- packages/picasso.js/src/core/chart-components/legend-cat/item-renderer.js
Improves alignment between shape and text in categorical legend.
Before:
After:
> fix(legend-cat): improve text and shape alignment

- packages/picasso.js/src/web/text-manipulation/__tests__/font-size-to-height.spec.js
- packages/picasso.js/src/web/text-manipulation/__tests__/line-break-resolver.spec.js
- packages/picasso.js/src/web/text-manipulation/__tests__/text-metrics.spec.js
- packages/picasso.js/src/web/text-manipulation/__tests__/word-break.spec.js
- packages/picasso.js/src/web/text-manipulation/font-size-to-height.js
- packages/picasso.js/src/web/text-manipulation/line-break-resolver.js
- packages/picasso.js/src/web/text-manipulation/text-const.js
- packages/picasso.js/src/web/text-manipulation/text-metrics.js
- packages/picasso.js/src/web/text-manipulation/word-break.js
Changes so that line height is computed based on the font-size instead of a computed text height. The result of this will be less space between each line than before and it will more closely resemble how line-height is handle in CSS.
> fix(text-metrics): computed line height

- packages/picasso.js/src/core/chart-components/legend-seq/__tests__/legend-seq.spec.js
- packages/picasso.js/src/core/chart-components/legend-seq/node-builder.js
Fixes an issue where the ticks on the sequential legend would not align properly. Removed component specific solution and instead use the baseline attribute to position the ticks.
> fix(legend-seq): misaligned ticks

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/index.js
**Checklist**
- brush from shapes based on the amount of components sent in. Basically allows multiple components sharing the same key, but different contexts to be brushed on.
> fix: brush based on the amount of components

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
This PR is to change baseline from 'alphabetical' to 'central' to have better placement of bar value label against a bar and avoid of using a "magic" number.
> fix(bar-label): update bar label position

- package.json
- renovate.json
- yarn.lock
Major releases for `rollup-plugin-commonjs@10.0.0` and `rollup-plugin-node-resolve@5.0.0` both depend on `rollup@1.12.0`.
> chore(deps): update rollup dependencies

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/slices.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
Fixes an issue, where under certain circumstances, no or very few labels would be rendered with an inside horizontal slices strategy.
There is no longer any restriction that a label should fit within a slice when the `direction` is horizontal and the `position` is inside. Instead there is a check if a label is overlapping or is within some threshold of another label.
> fix(labels): too few labels with horizontal inside slice strategy

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/slices.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
Fixes an issue where a label would sometimes be displayed as only the ellipsis character. There is now a minimum requirement for a label to contain at least 1 character plus the ellipsis character given the full label doesn't fit.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2019-06-07 at 10 34 04](https://user-images.githubusercontent.com/16608020/59092335-980dc780-8911-11e9-86dc-bbe4950a2c5b.png)  | ![Screenshot 2019-06-07 at 10 36 30](https://user-images.githubusercontent.com/16608020/59092348-9e9c3f00-8911-11e9-82cc-23903dea88e9.png)  |
|![Screenshot 2019-06-07 at 10 35 13](https://user-images.githubusercontent.com/16608020/59092336-980dc780-8911-11e9-9dd0-afcb9776df2b.png) | ![Screenshot 2019-06-07 at 10 36 …
> fix(labels): require label to contain at least first character

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
- packages/picasso.js/src/core/chart-components/property-resolver/index.js
Exposes a `defined` property for the line `coordinates` config which allows a user to specify when a coordinate is considered defined.
> feat(line): enable config of defined

- packages/picasso.js/src/core/chart-components/box/__tests__/box-shapes.spec.js
- packages/picasso.js/src/core/chart-components/box/box-shapes.js
The `show` method was evaluated per shape but the result was not used when determining visibility of it.
Fixes #411
> fix(box): evaluate show per shape

- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/theme/__tests__/theme.spec.js
- packages/picasso.js/src/core/theme/index.js
Enables style overrides on chart update:
```js
chart.update({
style: {
'$font-color': 'red'
}
})
```
> feat: add style overrides in definition

- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
There are two cases when a line should be interrupted:
Domain|Value
---|---
A|2
B|3
C|undefined
D|4
E|5
This case is easily handled today with `lineGenerator.defined`.
Domain|Value
---|---
A|2
B|3
D|4
E|5
Notice that the domain value **B** is missing. When the line is constructed all points on the line are defined so there will be no gaps.
There may however be cases when the domain on the major scale is different from the domain on the line and the line should reflect this by interrupting the line.
This PR implements the second case so that the two datasets above are rendered the same:
> feat(line): disconnect lines

- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
Exposes the collected points per layer which can be used for additional configurability:
```js
{
type: "line",
data: { /* */ },
settings: {
coordinates: {
major: { scale: "x" },
minor: { scale: "y" },
},
layers: {
line: {
strokeWidth(d) {
const points = d.datum.points; // 'points' contains all coordinate values for this layer
return points.length > 50 ? 2 : 4;
},
stroke(d) {
const max = Math.max(...d.datum.points.map(p => p.end.value));
return max > 100 ? 'green' : 'red';
},
},
},
},
}
```
> feat(line): add points to collected layers

- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
Use `major` prop in data if available when determining the continuity of a line's domain.
> feat(line): use major prop if available

- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-gradient.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-gradient.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-gradient.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-gradient.js
Allow use to set custom bounds on gradient:
```js
fill() {
return {
type: 'gradient',
x1: 0,
x2: 0.5,
y1: 0.5,
y2: 1,
stops: [{
color: 'blue',
offset: 0,
}, {
color: 'green',
offset: 1,
}]
}; 
}
```
> feat(gradient): support custom gradient bounds

- .eslintrc.json
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/rows.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/rows.js
- packages/picasso.js/src/core/scene-graph/display-objects/text.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/text.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-nodes.js
Rendering ellipsis only when text doesn't fit is weird and doesn't really add any value. This PR fixes so that ellipsed text that only contains the ellipsis character isn't rendered at all.
> fix(labels): avoid rendering ellipsis only

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
Overflow property is used to ignore checking if a label is fit into a rectangle.
So we should take this into account of finding best placement for labels.
> fix(bar-label): take overflow into finding best placement for bar label

- packages/picasso.js/src/core/chart-components/line/line.js
Fixes an issue where custom line sorting was not applied.
Old test cases still valid, just gave false positive before.
> fix: fix custom line sorting

- packages/picasso.js/src/core/geometry/__tests__/polygon.spec.js
- packages/picasso.js/src/core/math/narrow-phase-collision.js
The current algorithm does not work in the following cases:
1. the ray goes through a vertex
2. the point is the same as a vertex
3. the point is on a horizontal edge of the polygon
> fix(collision): fix checking point inside polygon

- packages/picasso.js/src/core/chart-components/legend-cat/__tests__/item-renderer.spec.js
- packages/picasso.js/src/core/chart-components/legend-cat/item-renderer.js
This PR is to fix calculating number of rows/columns of the categorical legend.
To make it easy, let assume it is horizontal legend.
The relationship between legend height and the number of rows is:
[Legend height] = [Number of rows] * [Row height] + ( [Number of rows] - 1 ) * Margin
where Margin is the distance between rows.
If we know the legend height we can estimate the number of rows as the following:
[Number of rows] = Math.floor( ( [Legend height] + Margin ) / ( [Row height] + Margin ) )
> fix(legend): fix calculating legend size

- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/src/core/chart-components/legend-cat/navigation-renderer.js
Setting tabindex to -1 for legend navigation buttons to improve accessibility/keyboard navigation experienvce.
> refactor: adjust tabindex of legend nav

- docs/scriptappy.json
- packages/picasso.js/src/core/geometry/__tests__/polygon.spec.js
- packages/picasso.js/src/core/geometry/circle.js
- packages/picasso.js/src/core/geometry/geometry-collection.js
- packages/picasso.js/src/core/geometry/line.js
- packages/picasso.js/src/core/geometry/polygon.js
- packages/picasso.js/src/core/geometry/polyline.js
- packages/picasso.js/src/core/geometry/rect.js
This PR is to:
- rename geopolygon to polygon which is an array of vertices
This is to prepare to add geopolygon which is an array of polygons where the first polygon is an outer polygon and other polygons are inner polygons which represent holes in the outer polygon.
> refactor(polygon): rename geopolygon to polygon

- plugins/q/src/brush/__tests__/q-brush.spec.js
- plugins/q/src/brush/q-brush.js
This PR makes it possible to brush/select more that one column for pivot cells.
> fix(q-brush): allow multi select pivot columns

- docs/scriptappy.json
- packages/picasso.js/src/core/brush/__tests__/brush.spec.js
- packages/picasso.js/src/core/brush/brush.js
- packages/picasso.js/src/core/component/__tests__/brushing.spec.js
- packages/picasso.js/src/core/component/brushing.js
Add possibility to suppress picasso component render when doing brush.start and brush.end
> feat(brush): suppress paint on brush.end() and brush.start()

- plugins/hammer/src/__tests__/hammer-mock.js
- plugins/hammer/src/__tests__/hammer.spec.js
- plugins/hammer/src/__tests__/plugin.spec.js
- plugins/hammer/src/hammer.js
- plugins/hammer/src/index.js
When using the Hammer plugin for picasso, it was assumed that a global Hammer instance was available. However in some cases Hammer could be imported multiple times and thus multiple versions could be conflicting with each other.
Before, the Hammer instance was assumed a global so you could just register the plugin directly:
```js
import picasso from 'picasso.js';
import hammerPlugin from 'picasso-plugin-hammer';
picasso.use(hammerPlugin);
```
It is now possible to provide the Hammer instance to the plugin itself, and then register the result:
```js
import Hammer from 'hammerjs';
import picasso from 'picasso.js';
import hammerPlugin from 'picasso-plugin-hammer';
picasso.use(hammerPlugin(Hammer));
```
While it is still possible to do it the old way, the new approach is recommended.
> feat(hammer-plugin): provide Hammer instance

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
There is a need to decide the color of a label depending on if the label is overlapping with other objects. To be able to do that, in the fill color function, we need to know the label bound to support checking overlapping between the label and other objects.
> fix(bar-label): allow fill function accessing label bound to support checking overlapping

- packages/picasso.js/src/core/chart-components/ref-line/__tests__/refline.spec.js
- packages/picasso.js/src/core/chart-components/ref-line/refline.js
Add the possibility to specify value as a function for the ref-line component.
**Checklist**
> feat: ref-line value as a function

- packages/picasso.js/package.json
- yarn.lock
Revert to d3-shape v1.3.6 since v1.3.7 causes an issue in stack ([change](https://github.com/d3/d3-shape/commit/bf15db4a8db7ce393db6d6d77bdf953e4e78b13d)) order when used i line/area chart.
> chore: revert d3-shape version

- packages/picasso.js/src/core/chart-components/point/__tests__/point.spec.js
- packages/picasso.js/src/core/chart-components/point/point.js
Allows `shape` property to be a function that returns an object to enable resolving of shape specific properties. Requires `type` to be on of the properties.
Example:
```js
settings: {
shape: () => ({
type: 'n-polygon',
sides: 5,
startAngle: 90,
}),
}
```
> feat(point): resolve shape with custom properties

- .eslintrc.json
This is mainly to enable the use of optional chaining in picasso.js like:
`obj.val?.prop` instead of writing `obj.val && obj.val.prop`
> chore: set "babel-eslint" as parser

- plugins/q/src/data/__tests__/extractor-t.spec.js
- plugins/q/src/data/extractor-t.js
Additional checks to avoid problem during data extraction for tree data nodes that are missing qAttrDims or qAttrExps.
> fix: avoid problem during tree data extraction

- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-nodes.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-nodes.js
SVG and canvas renders shapes slightly different when some of the attributes are not numbers or formatted in odd ways. This fixes the most common case and that is `NaN` value. There are still edge cases where it will differ, especially between browser, for example setting `x = '   100   '` will render in some browser but not in others.
> fix: handle NaN in svg renderer

- studio/src/components/QDataArea/QDataArea.jsx
- studio/src/components/RenderingArea/RenderingArea.jsx
This PR is support accessing the layout of a Qlik chart inside settings so settings can adapt to the chart layout (e.g. number of dimensions, measures, or max/min value of a measure).
> fix: allow accessing the layout of a Qlik chart inside settings

- packages/picasso.js/package.json
- renovate.json
- yarn.lock
d3-shape v1.3.7 has an unwanted side-effect because of the following change made to it:
```md
Before: Positive values are stacked above zero, while negative values are stacked below zero
Now: Positive values are stacked above zero, negative values are stacked below zero and zero values are stacked at zero.
```
This PR reverts the version bump and locks renovate to the correct version.
> chore: revert d3-shape version bump

- packages/picasso.js/src/core/component/__tests__/brushing.spec.js
- packages/picasso.js/src/core/component/brushing.js
- plugins/q/src/brush/__tests__/q-brush.spec.js
- plugins/q/src/brush/q-brush.js
This PR is to allow combining range selections by using OR mode or AND mode. Currently picasso.js supports only OR mode. However, AND mode is needed for example when we want to combine two range selections, each for a measure axis in a scatter plot.
> feat: support AND/OR mode for range selections

- docs/scriptappy.json
- packages/picasso.js/src/api/components.js
- packages/picasso.js/src/core/chart-components/container/container.js
- packages/picasso.js/src/core/chart-components/container/index.js
- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/__tests__/component-collection.spec.js
- packages/picasso.js/src/core/chart/component-collection.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/layout/dock/__tests__/dock-layout.spec.js
- packages/picasso.js/src/core/layout/dock/config.js
- packages/picasso.js/src/core/layout/dock/docker.js
- studio/src/examples/multi-legend.js
- studio/src/examples/trellis.js
Add Support for Components in Components (#181)
A simpler more limited alternative to https://github.com/qlik-oss/picasso.js/compare/master...nilzona:compose-api
**Checklist**
> Nested layout

- docs/package.json
When a release is created today the api spec has a version that is out-of-sync with the released version. This is an attempt to fix that by building the spec as a part of the `lerna version` lifecycle.
Also removed the call to the `gen` script as that is no longer needed.
> chore(docs): build spec on publish

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/chart/scales/index.js
- packages/picasso.js/src/core/data/collections.js
- packages/picasso.js/src/core/data/dataset.js
- packages/picasso.js/src/core/formatter/index.js
This PR adds two new definitions for extracting data `DataExtraction` and `DataFieldExtraction`. The previously documented definition was not really reflecting reality.
> docs: add data extraction type

- docs/package.json
- docs/scriptappy.json
Build script for the website package is dependent on the output of the `gen` script so I have to add it again.
> chore: fix build script for docs

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/__tests__/component-collection.spec.js
- packages/picasso.js/src/core/chart/component-collection.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/component/__tests__/component-factory.spec.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-buffer.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-renderer.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-buffer.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/dom-renderer/__tests__/dom-renderer.spec.js
- packages/picasso.js/src/web/renderer/dom-renderer/dom-renderer.js
- packages/picasso.js/src/web/renderer/index.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-renderer.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/test-utils/mocks/canvas-context.js
This makes it possible to trigger a "light" rendering of specific components, where only a transform is applied. The reason is to provide smoother rendering performance for charts containing components with a lot of nodes. This approach might be applicable while interacting with a chart where you want to redraw the chart continuously and maintain a responsive feeling.
Here is an example of how it can affect performance (a simple scatterplot with 2000 nodes) where chart rendering time went from 80 ms to 5 ms (the bottom one uses transfoms):
```js
componentDef: {
...,
rendererSettings: {
transform: () => ({ a: 1, b: 0, c: 0, d: 1, e: 100, f: 100 }),
canvasBufferSize: { width: 1000, height: 800 },
}
};
chart.update({ partialData: true });
```
**Checklist**
> feat: transformation setting for components

- azure-pipelines.yml
- package.json
- yarn.lock
The protractor tests running IE11 in Azure DevOps suddenly started failing around ~20210818 (after a new VM image was introduced in Azure DevOps with a new version of IE web driver).
Installing an explicit version of the iedriver solves the problem.
> test: set explicit iedriver version

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
Add setting `orientation` to bar strategy for labels. It specifies the orientation of the displayed text. For example, forces horizontal text for a label displayed above a point.
**Checklist**
> feat: add orientation setting for bar strategy

- packages/picasso.js/src/core/layout/dock/docker.js
**Checklist**
From Node11, the arguments passed to the compare function of `Array.sort()` are reversed. 
(See: https://github.com/nodejs/node/issues/24294)
Therefore the code inside the compare function should be made independent of the arguments order, so that it is independent of the node version.
> fix: node version dependent sorting

- packages/picasso.js/src/core/chart/__tests__/chart.spec.js
- packages/picasso.js/src/core/chart/__tests__/component-collection.spec.js
- packages/picasso.js/src/core/chart/component-collection.js
- packages/picasso.js/test/helpers/component-factory-fixture.js
**Checklist**
- [not relevant] documentation updated
Currently the renderer settings (for example, for canvas renderer: https://github.com/veinfors/picasso.js/blob/bb628a6b981c62109c68982273882986dbb00a67/packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js#L169) are only updated when a component is created. It means when a component changes (due to for example a range selection), the renderer settings, especially the transform function, is oudated. This PR is to fix that issue.
Before fix:
https://user-images.githubusercontent.com/70384379/141995711-b05766df-4d19-4443-93cc-def085bcf26a.mov
After fix:
https://user-images.githubusercontent.com/70384379/141995541-34064bd5-3f0c-487a-ac78-1a52537fc5b0.mov
> fix(transformation): update renderer settings after a component has changed

- plugins/q/src/data/__tests__/field.spec.js
- plugins/q/src/formatter/__tests__/formatter.spec.js
- plugins/q/src/formatter/__tests__/numberFormat.spec.js
- plugins/q/src/formatter/index.js
- plugins/q/src/formatter/parts/qs-number-formatter.js
**Checklist**
To fix https://jira.qlikdev.com/browse/QB-6534
Currently, any 'A' character in the format expression will force the number to adopt SI abbreviation. This seems to be an overkill. 
To give customers more freedom to use character 'A', we can restrict the SI abbreviation syntax: only when 'A' is right after format code, which uses either '#', '0', or non-breaking space. This restricted syntax is in accordance with what has been planned for the SI abbreviation syntax, see in the same file at:
https://github.com/qlik-oss/picasso.js/blob/02620ff4f8e3c89e14539bc2387c0524599322a8/plugins/q/src/formatter/parts/qs-number-formatter.js#L278
> fix: support SI abbreviation only when format is auto or type is 'U'

- .prettierignore
- docs/scriptappy.json
**tl;dr**
Disable formatting of api specification and update it with the format used by scriptappy. After this change running `yarn spec` yields no change in the api specification.
More details... Using scriptappy to generate the api specification provides an output on a specified format. When committing the api specification the precommit hook ran prettier which formatted it slightly. The source controlled file is on the prettier format. As a result of this when generating the api specification again it differs, although no actual change has been done to the spec.
**Checklist**
> fix: ignore api spec and checkin with scriptappy format

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/axis/axis-default-settings.js
- packages/picasso.js/src/core/chart-components/box/index.js
- packages/picasso.js/src/core/chart-components/brush-lasso/brush-lasso.js
- packages/picasso.js/src/core/chart-components/container/container.js
- packages/picasso.js/src/core/chart-components/grid/index.js
- packages/picasso.js/src/core/chart-components/labels/labels.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
- packages/picasso.js/src/core/chart-components/labels/strategies/rows.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
- packages/picasso.js/src/core/chart-components/legend-cat/index.js
- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/src/core/chart-components/legend-seq/index.js
- packages/picasso.js/src/core/chart-components/line/index.js
- packages/picasso.js/src/core/chart-components/pie/pie.js
- packages/picasso.js/src/core/chart-components/point/index.js
- packages/picasso.js/src/core/chart-components/point/point.js
- packages/picasso.js/src/core/chart-components/ref-line/index.js
- packages/picasso.js/src/core/chart-components/text/text.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/data/data.js
- packages/picasso.js/src/core/data/dataset.js
- packages/picasso.js/src/core/scales/band.js
- packages/picasso.js/src/index.js
- packages/picasso.js/src/web/components/brush-area/index.js
- packages/picasso.js/src/web/components/brush-range/index.js
- packages/picasso.js/src/web/components/tooltip/index.js
*Overview*
The JSDoc has been updated in a number of places to better describe the API. For example, when configuring picasso.js the logging parameter is optional. More work can be done in this area to improve the DX.
This is done as a preparation in order to be able to [generate typescript definitions](https://github.com/qlik-oss/picasso.js/pull/670) for Picasso.js.
**Checklist**
> docs(picasso.js): update jsdoc to align with implementation

- docs/package.json
- packages/picasso.js/types/index.d.ts
- yarn.lock
Update dependency `@scriptappy/to-dts` in order to include disclaimer message in generated typescript definition file:
```
// File generated automatically by "@scriptappy/to-dts"; DO NOT EDIT.
```
Note; also added `@scriptappy/cli` as dependency in order to make `sy` a runnable command. Previously it worked due to linked repos.
**Checklist**
> feat(to-dts): include disclaimer in ts defs

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/component/__tests__/brushing.spec.js
- packages/picasso.js/src/core/component/brushing.js
Add a  function called `sortNodes` in brush config.
```
{
consume: [
{
data,
context: 'selection',
mode: 'and',
style: {
inactive: {},
active: {},
},
},
],
sortNodes: (obj) => {
return sortedNodes;
},
};
```
> feat: add sortNodes function in brush config

- azure-pipelines.yml
the old image was removed June 30, 2022
**Checklist**
> chore: update azures-pipline-image

- plugins/q/src/data/extractor-t.js
Fix data not showing in two dimensional grouped bar chart when data has same qText.
The issue
After fixing showing in nebula
**Checklist**
> fix: same key issue when extract data

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/slices.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
**Checklist**
This problem is related to animations.
Current maxWidth setting for slice label rect is not enough, leading to some labels becoming ellipsed during animations. Simply increase this maxWidth by one pixel solves the issue.
- Before fix: (The video has been slowed down ~ 30 times from real time)
https://user-images.githubusercontent.com/70384379/185360897-7700496a-3d8b-4a6c-b4ca-2a83ae2b49b2.mp4
- After fix: (The video has been slowed down ~ 30 times from real time)
https://user-images.githubusercontent.com/70384379/185361157-5b25bcdb-75a3-41c2-9d3a-2db0b01a4af1.mp4
> fix: increase max width for slice label

- packages/picasso.js/src/core/chart-components/pie/__tests__/pie.spec.js
- packages/picasso.js/src/core/chart-components/pie/pie.js
- packages/picasso.js/src/core/component/tween.js
- packages/picasso.js/src/core/scene-graph/display-objects/__tests__/path.spec.js
- packages/picasso.js/src/core/scene-graph/display-objects/path.js
**Checklist**
This PR fixes two main problems with animations:
- Animations of a pie chart's slices: (Issue: https://github.com/qlik-trial/la-vie/issues/4387)
- Issue: currently the path that represents a slice (`slice.d`) is a string and is calculated in the pie component (src/core/chart-components/pie/pie.js). During pie chart animations, the tween slices are interpolated from this string, which is not nice (see the first video below)
- The fix: it would be better to interpolate the actual slice (start angle, end angle, radius) instead of the slice.d string. We can achieve this by calculating `slice.d` in the display path (src/core/scene-graph/display-objects/path.js) instead of in the pie component.
- Improve the transitions:
- Issue: currently the transition stage still happens even …
> fix(animations): improvements

- packages/picasso.js/src/core/geometry/circle.js
- packages/picasso.js/src/core/geometry/geometry-collection.js
- packages/picasso.js/src/core/geometry/geopolygon.js
- packages/picasso.js/src/core/geometry/line.js
- packages/picasso.js/src/core/geometry/polygon.js
- packages/picasso.js/src/core/geometry/polyline.js
- packages/picasso.js/src/core/geometry/rect.js
- packages/picasso.js/src/core/scene-graph/scene-node.js
#665 change how some classes got exported. For some reason which I do not understand currently. That results in a different JSDoc output then expected.
This PR changes it back to a syntax which does produce the correct JSDoc output.
> refactor: change class export

- packages/picasso.js/src/core/component/brushing.js
This PR to support styling brushed nodes (e.g. border width/color) based on active nodes. E.g. in a scatter plot, the border of active nodes should be smaller when the number of active nodes are bigger.
> feat: support styling brushed nodes based on active nodes

- packages/picasso.js/src/core/chart/component-collection.js
Currently there is a limitation on using chart.layoutComponents and chart.update together.
For example we want to layout all components and then render light components in one chart.update and then render heavy components in a series of chart.update with progressive mechanism.
The current problem is that :
1. First, we run chart.layoutComponents (without using excludeFromUpdate) to layout all components, all components have updateWith property which is used to render the components in next chart.update.
2. Second, we run chart.update with excludeFromUpdate with intension that we want to render few components and exclude other components from updating. However, with updateWith calculated from chart.layoutComponents, excludeFromUpdate is not used to exclude a component from update. …
> fix: should take excludeFromUpdate into account for update

- packages/picasso.js/src/core/chart-components/grid/line.js
**Checklist**
For a dimension axis (grid chart has two, for example),  value of the grid line is in `p.data`, not directly in `p`.
> fix: grid line value for dimension axis

- packages/picasso.js/src/core/component/tween.js
**Checklist**
When animating a chart, there is an issue when the main component has no node in updating stage: the chart looks blank for 0.4 seconds. The logics for removing updating stage in this case has been implemented before (https://github.com/qlik-oss/picasso.js/pull/722). This PR improves it even more.
- Allow filtering scene nodes of the main component. For example, the `sankey` component can have many types of scene nodes, from which we are only interested in `path` nodes.
- Allow multiple main components. For example, a combo chart can have both line and bar component. We only remove the updating stage if each of the main components has no node in updating stage.
- Only apply removing updating stage logics to the path nodes of sankey component. 
- Before: all scene nodes of the …
> fix: improve tweening when removing updating stage

- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
**Checklist**
Bullet chart has background rect for labels, due to the fact that a bullet can have multiple colors.
To animate these rects, we need to give IDs for them: https://github.com/qlik-trial/la-vie/blob/master/chart-modules/animations/src/labels/track-by.js#L7
This PR is to provide the info needed to ID these rects.
> fix: more info for label bg rect, to support chart animations

- packages/picasso.js/package.json
- packages/picasso.js/src/core/component/__tests__/interpolate-object.spec.js
- packages/picasso.js/src/core/component/interpolate-object.js
- packages/picasso.js/src/core/component/tween.js
**Checklist**
_**The issuse:**_ This bug is because the D3-interpolation package that we use for animations treats a string like "Red" as a color and attempts to interpolate it in the RGB form.
_**The fix:**_ Write a custom interpolate object function based on that in D3-interpolate, but modify the piece of code that attempts to interpolate string as color. This issue of interpolating any string containing color word as RBG has been raised some times (for e.g.: https://github.com/d3/d3-interpolate/issues/42) but D3 leader Mike Bostock does not want make the string interpolation, or any other types of interpolation, more customizable. To quote his words: "It feels a little too specific to me, as-is."
- That it solves the problem.
- Before: …
> fix: animations avoid interpolating color

- plugins/q/src/data/__tests__/extractor-s.spec.js
- plugins/q/src/data/extractor-s.js
**Checklist**
When `qColumnOrder` for chart with data in S-mode in not an empty array, the order of `qDataPages` is influenced by `qColumnOrder` and this should be taking into account when reading rows.
> fix: get correct index when columnOrder is irregular

- .circleci/config.yml
- packages/picasso.js/src/web/components/tooltip/__tests__/placement.spec.js
- packages/picasso.js/src/web/components/tooltip/placement.js
This is a special case for Treemaps as there as a branch could cover the whole area available and tooltip cannot be then docked in the available positions - top, bottom, left & right.
So a new dock position is added as "ínside" where the tooltip is shown in the center of the object. Also I have removed the arrow used to dock on particular positions as we are already in the object now.
Attached is a screenshot :
> fix: show the tooltip inside the object when its takes up the whole screen

- packages/picasso.js/package.json
- renovate.json
- yarn.lock
When using the latest version of `preact`, the tooltip component stopped working properly. It would only render once when hovering a node. The second time a node was hovered, the tooltip would not appear. Downgrading `preact` fixes that issue.
> fix: downgrade preact

- packages/picasso.js/src/core/chart-components/ref-line/__tests__/refline.spec.js
- packages/picasso.js/src/core/chart-components/ref-line/lines-and-labels.js
- packages/picasso.js/src/core/chart-components/ref-line/oob.js
- packages/picasso.js/src/core/chart-components/ref-line/refline.js
> fix: fix slope line

- packages/picasso.js/src/core/scene-graph/attributes.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/text.js
- packages/picasso.js/src/web/text-manipulation/text-metrics.js
This PR to support measure text with styling e.g bold and/or italic
**Checklist**
> feat: support measuring text with font weight

- packages/picasso.js/src/web/text-manipulation/text-ellipsis.js
**Checklist**
Problem description: 
The text-ellipsis function expects text-related properties such as font-size and font-family to be in kebab-case (e.g., font-size, font-family). However, the application sometimes (for example in rows.js) provides these properties in camelCase (e.g., fontSize, fontFamily), leading to errors in text measurement and rendering.
This PR resolves the issue by normalizing the font property names. A fallback mechanism has been added to allow the function to handle both kebab-case (preferred) and camelCase properties, ensuring proper text measurement and ellipsis functionality.
Before: 
https://github.com/user-attachments/assets/7033c5ad-fde7-4d95-a0a7-b1d996c1fe37
After: 
https://github.com/user-attachments/assets/9163521c-7067-498d-81f8-ad945a55811e
> fix: correct ellipsis property extraction logic

- packages/picasso.js/src/core/component/animations/__tests__/adjust-tweened-node.spec.js
- packages/picasso.js/src/core/component/animations/adjust-tweened-nodes.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/core/component/tween.js
**Checklist**
**The issue:**
Considering animating a formatted numerical label, say from "4.5M" to "123k". The out-of-the-box d3 string interpolator produces wrong tweened results: super long strings with questionable values.
**The fix:**
- Take advantage of the linkData properties to pass data into label nodes (the nodes are defined when creating picasso-definition for a chart)
- Replace the wrongly interpolated text with the formatted tweened value from linkData.
> fix: animations improve tweening formatted label

- packages/picasso.js/src/core/data/extractor.js
Currently if we use an array as data input like the following  
```
data: [
{ x: 'Jan', y: 365, lineId: 0 },
{ x: 'Feb', y: 372, lineId: 0 },
{ x: 'Jun', y: 380, lineId: 1 },
{ x: 'Sep', y: 370, lineId: 1 },
]
```
Then picasso will convert this to:
```
[
{ value: { x: 'Jan', y: 365, lineId: 0 }, label: '[object Object]' },
{ value: { x: 'Feb', y: 372, lineId: 0 }, label: '[object Object]' },
{ value: { x: 'Jun', y: 380, lineId: 1 }, label: '[object Object]' },
{ value: { x: 'Sep', y: 370, lineId: 1 }, label: '[object Object]' },
]
```
To keep the raw input we input as the following:
```
data: {
items: [
{ x: 'Jan', y: 365, lineId: 0 },
{ x: 'Feb', y: 372, lineId: 0 },
{ x: 'Jun', y: 380, lineId: 1 },
{ x: 'Sep', y: 370, lineId: 1 },
],
skipNormalize: true,
}  
```
There is a need to keep …
> feat: support raw input

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/ref-line/__tests__/refline.spec.js
- packages/picasso.js/src/core/chart-components/ref-line/lines-and-labels.js
- packages/picasso.js/src/core/chart-components/ref-line/refline.js
- packages/picasso.js/types/index.d.ts
This PR changes so sloped ref-lines use the same documented label properties as normal ref-lines.
Before this PR sloped ref-lines used these undocumented properties:
```
{
refLineLabel: 'label',
showLabel: true,
showValue: true,
labelStroke: 'red',
}
```
Instead of the documented properties that already exist and are used by normal ref-lines:
```
label: {
text: 'label',
show: true,
showValue: true,
stroke: 'red'
}
```
> refactor(ref-line): use documented properties

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
**Checklist**
In current bar label strategy code, when the label is oriented vertically, it is assumed to dock left. In other words, if you have a vertical bar and you label it with a vertical label, the direction of the text is such that you can read it easily when you tilt your head to the left. However, there are cases where you want to dock the text to the right of the bar. This PR enables that option by adding a new property named `dock` to the label settings.
Before: the text is difficult to read if it is docked to the right of the bar, since the text direction follows the assumption that it is docked left.
After:
> fix: bar label strategy dock right

- packages/picasso.js/src/core/scene-graph/display-objects/circle.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/__tests__/image.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/shapes/image.js
**Checklist**
This PR fixes a number of bugs found when testing the image plugin. 
1. Image not positioning correctly. 
Before: 
https://github.com/user-attachments/assets/499b798f-51ac-4312-9e91-8a3803f38b30
After: 
https://github.com/user-attachments/assets/c2752a7d-1b6b-4005-878e-4a6f26d091e7
2. Keep aspect ratio when rendering the image as a circle. 
Before: 
https://github.com/user-attachments/assets/7cdb9df1-5d34-41f5-880b-f349e3c787aa
After: 
https://github.com/user-attachments/assets/56849684-fa06-46c9-bb5c-2bf18b93b3b1
3. Also removed rendering the image on an offscreen canvas before rendering it to the visible canvas. The reason for that is that it caused a bug where sometimes the image did not render on refresh, when having two objects with a rendered image in the same window.
> fix: image position and preserving image aspect ratio
