qlik-oss/picasso.js

- .circleci/config.yml
> chore: disable test coverage report

- website/core/Footer.js
- website/i18n/en.json
- website/pages/en/examples.js
- website/siteConfig.js
- website/static/css/custom.css
Added a gallery of examples on website
> docs: add examples

- README.md
Add link to examples on website in README.md
> docs: Add link to examples on website in README.md

- website/pages/en/examples.js
> docs: fix broken example links

- website/pages/en/index.js
- website/static/css/custom.css
- website/static/img/components-continuous.svg
- website/static/img/components-discrete.svg
- website/static/img/components-h-title.svg
- website/static/img/components-labels.svg
- website/static/img/components-legend.svg
- website/static/img/components-reference.svg
- website/static/img/components-titles.svg
- website/static/img/components-v-title.svg
- website/static/js/landing.js
- Fixes missing logos on small devices
Fixes #6
Might fix #7
> docs: fix missing logo issue on small devices

- docs/dist/plugin-hammer.md
- docs/dist/plugin-q.md
- docs/src/input/plugin-hammer.md
- docs/src/input/plugin-q.md
- packages/picasso.js/README.md
- plugins/hammer/readme.md
- plugins/q/README.md
- plugins/q/src/index.js
Update README per public package
*Need to find way to auto-copy files instead of manual copy/paste*
> docs: update README in packages

- README.md
- website/siteConfig.js
Enables https for website
Closes #8
> chore: default url to https

- website/core/Footer.js
- website/pages/en/index.js
- website/static/css/custom.css
Added buttons to "Get started" and "Examples"
> docs: add promo buttons

- website/i18n/en.json
- website/pages/en/index.js
- website/siteConfig.js
- website/static/css/custom.css
Change tagline to _Turn your data into a visual masterpiece_
> docs: change tagline

- website/siteConfig.js
- website/static/css/custom.css
Enable Algolia search with a custom styling.
> docs: enable Algolia search

- docs/dist/component-box.md
- docs/dist/data.md
- docs/src/input/component-box.md
- docs/src/input/data.md
- packages/picasso.js/src/core/chart-components/box/box-resolver.js
- packages/picasso.js/src/core/chart-components/box/box-shapes.js
- packages/picasso.js/src/core/chart-components/box/box.js
- packages/picasso.js/src/core/chart-components/property-resolver.js
- packages/picasso.js/src/core/component/settings-resolver.js
- packages/picasso.js/test/unit/core/chart-components/box/box-resolver.spec.js
- packages/picasso.js/test/unit/core/chart-components/box/box.spec.js
- packages/picasso.js/test/unit/core/chart-components/line.spec.js
- packages/picasso.js/test/unit/core/chart-components/point/point.spec.js
- packages/picasso.js/test/unit/core/chart-components/property-resolver.spec.js
- packages/picasso.js/test/unit/core/component/settings-resolver.spec.js
> refactor: change context in datum callbacks

- docs/dist/component-brush-area-dir.md
- docs/dist/component-brush-range.md
- docs/spec.json
- docs/src/input/component-brush-area-dir.md
- docs/src/input/component-brush-range.md
`deltaX` and `deltaY` are also required event properties.
> docs: add required event properties

- packages/picasso.js/src/core/chart-components/legend-cat/item-renderer.js
- packages/picasso.js/src/core/chart-components/legend-cat/legend-cat.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/test/unit/core/chart-components/legend-cat/legend-cat.spec.js
Fixes an issue with the legend where the contents of the internal renderers are duplicated on show/hide.
> fix: legend title is duplicated

- lerna.json
- package-lock.json
- package.json
- packages/picasso.js/package.json
- plugins/hammer/package.json
- plugins/q/package.json
- Fixes `version` script to include modified `src/about` in commit
- Adds `prepublishOnly` tasks to ensure `/dist` is built with proper banner
> chore: automate release tasks

- .editorconfig
This has been bugging me for some time now...
> chore: Update to 2 space indentation in comment

- website/pages/en/examples.js
Added range brushing and labeling bars example
> docs: add more examples

- packages/picasso.js/src/core/chart-components/legend-cat/legend-layout.js
- packages/picasso.js/src/core/chart-components/legend-cat/navigation-renderer.js
- packages/picasso.js/test/unit/core/chart-components/legend-cat/legend-layout.spec.js
Improves alignment of items in a horizontal categorical legend with overflow
**Checklist**
> fix(legend-cat): improve alignment of content

- docs/package-lock.json
> chore: update dependencies

- docs/dist/scales.md
- docs/spec.json
- docs/src/input/scales.md
Found minor spelling issues when reading through the doc.
> docs: Minor spelling fix

- .circleci/config.yml
**Checklist**
- [ 👎 ] tests added
- [ 👍  ] commits conform to the [commit guidelines](./CONTRIBUTING.md#commit)
- [ 👎 ] documentation updated
> Auto deploy documentation

- plugins/q/src/data/dataset.js
- plugins/q/src/data/extractor-k.js
- plugins/q/test/unit/extractor-k.spec.js
> fix(q): extracting data from empty K cubes throws error

- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/test/unit/core/chart-components/legend-cat/legend-resolver.spec.js
Bugfix to make brushing on threshold legend values work correctly
> fix(legend-cat): threshold legend wrong brush source bugfix

- packages/picasso.js/src/core/charts/chart.js
- packages/picasso.js/test/component/chart/brushing.comp.js
this makes it possible to the component to get click event on touche devices
> feat(brush-trigger): Component level flag to disable brush triggers

- packages/picasso.js/src/core/charts/chart.js
- packages/picasso.js/src/core/theme/index.js
Exposes a minimal theme API on the chart instance.
> feat: expose theme on chart instance

- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
- packages/picasso.js/test/unit/core/chart-components/legend-cat/legend-resolver.spec.js
> fix: legend-cat formatter

- packages/picasso.js/src/core/chart-components/legend-cat/navigation-renderer.js
> fix(legend-cat): Remove commented import

- package-lock.json
- packages/picasso.js/package.json
> chore: update path-2d-polyfill

- packages/picasso.js/src/core/chart-components/labels/strategies/rows.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/rows.spec.js
> fix(label-strategy): Fix error when using rows strategy on non circle slices

- packages/picasso.js/src/core/charts/chart.js
> fix(layout): do not re-position components on partial data update

- docs/spec.json
- packages/picasso.js/src/core/chart-components/line/line.js
- packages/picasso.js/test/unit/core/chart-components/line.spec.js
> feat: add strokeDasharray as option to line component

- docs/gen.js
> chore: add code contrib comment

- docs/src/input/dock-layout.md
> docs: update layoutModes in dock-layout

- package-lock.json
- package.json
- packages/picasso.js/package.json
- plugins/hammer/package.json
- plugins/q/package.json
> chore: use cross-env for windows compatibility

- packages/picasso.js/src/core/chart-components/labels/strategies/rows.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/rows.spec.js
> fix(labels): Fix crash on empty labels in rows strategy

- packages/picasso.js/src/core/scene-graph/display-objects/path.js
> fix(scenegraph): allow small rounding errors in polygon detection

- packages/picasso.js/src/core/chart-components/legend-cat/navigation-renderer.js
> fix(legend-cat): Handle RTL using dir instead of .reverse()

- plugins/q/src/formatter/index.js
- plugins/q/test/unit/formatter/formatter.spec.js
> fix(q): use abbreviation pattern when qNumFormat.qType is U

- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
- packages/picasso.js/test/unit/core/chart-components/labels/strategies/slices.spec.js
From skipping labels to move labels and add a line
From:
To:
**Checklist**
> feat(labels): Change overlap, for outside label strategy for pie slices

- lerna.json
- package-lock.json
- package.json
> chore(deps): bump major version on lerna

- website/core/Footer.js
- website/package.json
- website/siteConfig.js
- website/static/css/custom.css
- Add edit link
- Fix image scaling in footer
- Fix background color on active header tab
> docs: minor docusaurus update

- packages/picasso.js/src/core/charts/chart.js
- packages/picasso.js/test/unit/core/charts/chart.spec.js
Checks if a component exists before trying to render it.
A warning will be logged if it does not exist - to enable logging of warnings in the console:
```js
const pic = picasso({
logger: {
level: 2
}
});
```
```js
pic.chart({
element,
data: []
settings: {
components: [{
type: 'oops'
}]
}
});
//  Unknown component: oops
```
fixes #80
> feat: check component existence before trying to create it

- .circleci/config.yml
- package.json
- yarn.lock
> chore: upload test results to circleci

- docs/src/input/brushing.md
- packages/picasso.js/src/core/component/brushing.js
- packages/picasso.js/test/unit/core/component/brushing.spec.js
> feat: support functions in brush style props

- packages/picasso.js/src/api/components.js
- packages/picasso.js/src/core/chart-components/debug/__test__/debug-collider.spec.js
- packages/picasso.js/src/core/chart-components/debug/__test__/debug-path-to-points.spec.js
- packages/picasso.js/src/core/chart-components/debug/debug-collider.js
- packages/picasso.js/src/core/chart-components/debug/debug-path-to-points.js
- packages/picasso.js/src/core/chart-components/debug/index.js
> feat: add debug components

- packages/picasso.js/src/core/chart-components/axis/axis-node-builder.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
- packages/picasso.js/src/core/chart-components/labels/strategies/slices.js
- packages/picasso.js/src/core/chart-components/ref-line/lines-and-labels.js
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/core/geometry/circle.js
- packages/picasso.js/src/core/geometry/line.js
- packages/picasso.js/src/core/geometry/polygon.js
- packages/picasso.js/src/core/geometry/polyline.js
- packages/picasso.js/src/core/geometry/rect.js
- packages/picasso.js/src/core/math/__tests__/narrow-phase-collision.spec.js
- packages/picasso.js/src/core/math/narrow-phase-collision.js
- packages/picasso.js/src/web/components/brush-area/brush-area.js
- packages/picasso.js/src/web/components/brush-range/brush-range-interaction.js
> refactor: split collision logic to separate modules

- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
> fix: update line settings

- packages/picasso.js/src/core/scales/__tests__/band.spec.js
- packages/picasso.js/src/core/scales/band.js
> feat: add range option for band scale

- package.json
Specify versions for yarn and node
> chore: add engines dependencies

- renovate.json
Tell renovate to not update node and yarn versions
> chore(renovate): disable engines

- .circleci/config.yml
- .eslintrc.json
- aw.config.js
- package.json
- packages/picasso.js/src/core/chart/index.js
- test/aw.config.js
- test/integration/interactions/events.fix.html
- test/integration/interactions/interaction.int.js
- yarn.lock
Removes the default event handlers when turning off interactions.
> fix(events): turn off default event handlers

- .github/CONTRIBUTING.md
**Checklist**
- Specify yarn version required by picasso.js
> docs: specify yarn version

- packages/picasso.js/src/core/data/__tests__/collections.spec.js
- packages/picasso.js/src/core/data/collections.js
Change so that data collections are evaluated only when requested
> perf(data): lazy evaluate collections

- aw.config.js
- packages/picasso.js/src/core/utils/event-type.js
Fix touch support on hybrid.
Issue caused by https://www.chromestatus.com/feature/4764225348042752
> fix(events): fix touch detection on hybrid

- packages/picasso.js/src/core/component/brushing.js
- packages/picasso.js/src/core/scene-graph/__tests__/node-container.spec.js
- packages/picasso.js/src/core/scene-graph/node-container.js
- packages/picasso.js/src/core/scene-graph/node.js
> perf: remove usage of concat

- docs/scriptappy.json
- packages/picasso.js/src/core/scene-graph/display-objects/__tests__/gradient-item.spec.js
- packages/picasso.js/src/core/scene-graph/display-objects/__tests__/pattern-item.spec.js
- packages/picasso.js/src/core/scene-graph/display-objects/display-object.js
- packages/picasso.js/src/core/scene-graph/display-objects/gradient-item.js
- packages/picasso.js/src/core/scene-graph/display-objects/index.js
- packages/picasso.js/src/core/scene-graph/display-objects/pattern-item.js
- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-gradient.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/__tests__/canvas-pattern.spec.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-gradient.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-pattern.js
- packages/picasso.js/src/web/renderer/canvas-renderer/canvas-renderer.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-gradient.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-pattern.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-gradient.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-nodes.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-pattern.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/test-utils/mocks/canvas-context.js
- packages/test-utils/mocks/element-mock.js
- Adds support for pattern in canvas and svg renderer
- Fixes svg gradients on brush
**Checklist**
> feat: add support for patterns

- plugins/q/src/formatter/__tests__/memoize.spec.js
- plugins/q/src/formatter/__tests__/numberFormat.spec.js
- plugins/q/src/formatter/memoize.js
- plugins/q/src/formatter/numberFormat.js
- plugins/q/src/formatter/parts/qs-number-formatter.js
> perf(q): memoize q-number-formatter

- packages/picasso.js/src/core/chart-components/box/box-shapes.js
> fix(box): remove Number.isNaN

- docs/src/input/component-brush-range.md
- packages/picasso.js/src/web/components/brush-range/__tests__/brush-area-dir.spec.js
- packages/picasso.js/src/web/components/brush-range/__tests__/brush-range.spec.js
- packages/picasso.js/src/web/components/brush-range/brush-range-interaction.js
- packages/picasso.js/src/web/components/brush-range/brush-range-node-builder.js
- packages/picasso.js/src/web/components/brush-range/brush-range.js
- test/integration/interactions/interaction.int.js
- test/integration/interactions/interactions-range.fix.html
This PR makes it possible to edit the bubbles in a range brush:
**Checklist**
> feat(brush-range): editable bubbles

- plugins/q/src/data/extractor-s.js
**Checklist**
- By switching for each loops to regular for loops inside extractor-s.js the following results was yielded when running performance benchmarks. This was tested on 500 field values.
for each loops
~ 2594 ops/s
for loops
~ 3763 ops/s
- In order to check out the metrics, please check out the branch located on this link and follow the instructions in README.md https://github.com/nguyenlam1/picasso.js/tree/perf-extractor-s/plugins/q/src/data
> perf(q): switch for each loops to regular for loops 

- docs/scriptappy.json
- docs/src/input/scale-linear.md
- packages/picasso.js/src/core/scales/ticks/__tests__/tick-generators.spec.js
- packages/picasso.js/src/core/scales/ticks/tick-generators.js
> feat(linear-scale): allow custom minor tick values

- packages/picasso.js/src/core/chart-components/legend-cat/legend-resolver.js
> refactor(legend-cat): remove unnecessary fn call to ordinary scales

- .eslintrc.json
- aw.config.ptor.js
- azure-pipelines.yml
- package.json
- test/protractor/sanity.spec.js
- test/protractor/serve.js
- test/protractor/setup.spec.js
- yarn.lock
Adds a basic protractor test in IE to ensure transpiled code can actually run.
> test: add protractor sanity test

- packages/picasso.js/src/core/chart-components/grid/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/grid/line.js
> fix(grid-line): broken for discrete scale

- packages/picasso.js/src/web/components/brush-range/__tests__/brush-area-dir.spec.js
- packages/picasso.js/src/web/components/brush-range/__tests__/brush-range.spec.js
- packages/picasso.js/src/web/components/brush-range/brush-range-node-builder.js
> fix(range-brush): show resize icon on bubble hover

- packages/picasso.js/src/core/scene-graph/display-objects/rect.js
> fix(scene-graph): zero as default rx/ry

- packages/picasso.js/src/core/chart-components/text/text.js
- packages/picasso.js/src/core/component/component-factory.js
> fix: text component issue

- packages/picasso.js/src/core/chart-components/labels/strategies/__tests__/bars.spec.js
- packages/picasso.js/src/core/chart-components/labels/strategies/bars.js
> feat(bar-labels): rounded background

- docs/src/input/data.md
- packages/picasso.js/src/core/data/__tests__/extractor.spec.js
- packages/picasso.js/src/core/data/extractor.js
output data from extract can now be filtered
**Checklist**
> feat: filter extracted data

- azure-pipelines.yml
> chore: set selenium version to avoid using 4.0.0-alpha

- packages/picasso.js/src/core/chart-components/box/__tests__/box.spec.js
- packages/picasso.js/src/core/chart-components/box/box.js
Update the order of rendering box components.
> fix(box): fix median component is rendered behind box component

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/line/__tests__/line.spec.js
- packages/picasso.js/src/core/chart-components/line/line.js
Adds option to draw connecting lines when undefined points interrupt the continuity.
> feat(line): add option to connect gaps in lines

- docs/src/input/scale-categorical-color.md
> docs: fix typo

- docs/src/input/scale-threshold-color.md
> docs: fix typo 

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/box/index.js
> docs:  property type should be boolean

- docs/src/input/component-legend-cat.md
> docs(legend-cat): update legend-cat with custom inline scale example

- packages/picasso.js/src/core/chart-components/legend-cat/__tests__/item-renderer.spec.js
- packages/picasso.js/src/core/chart-components/legend-cat/item-renderer.js
- packages/picasso.js/src/core/chart-components/legend-cat/legend-cat.js
- packages/picasso.js/src/core/chart-components/point/point.js
- packages/picasso.js/src/core/component/__tests__/component-factory.spec.js
- packages/picasso.js/src/core/component/component-factory.js
- packages/picasso.js/src/core/symbols/__tests__/symbols.spec.js
- packages/picasso.js/src/core/symbols/index.js
Fixes an issue where it was no longer possible to use custom symbols (#230) in any component after #369
> fix: unable to use custom symbols

- docs/src/input/component-axis.md
- packages/picasso.js/src/core/chart-components/axis/__tests__/axis.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis.js
> feat(axis): allow setting paddingStart and paddingEnd as either a func or a number

- packages/picasso.js/src/core/math/__tests__/cubic-bezier-curve-interpolation.spec.js
- packages/picasso.js/src/core/math/cubic-bezier-curve-interpolation.js
Improves handling of curves that are very large
> perf: improve curve to points

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/ref-line/__tests__/refline.spec.js
- packages/picasso.js/src/core/chart-components/ref-line/lines-and-labels.js
- packages/picasso.js/src/core/chart-components/ref-line/refline.js
This PR is to add dash style to a reference line.
> feat: support dash style for reference lines

- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-size-calculator.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis-label-size.js
- packages/picasso.js/src/core/chart-components/axis/axis.js
> fix: improve size used to detect tilted label overlap

- docs/scriptappy.json
- packages/picasso.js/src/core/data/dataset.js
Added additional types for the data extraction definition.
> docs: update api

- docs/package.json
Make sure that the spec file is included in the version commit
> chore(docs): update version script

- docs/scriptappy.config.js
- docs/scriptappy.json
> docs: update api stability and visibility

- docs/scriptappy.json
- packages/picasso.js/src/core/utils/registry.js
- packages/picasso.js/src/index.js
`registry` is a function and has been change to such
> docs: type change for registry

- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-line-node.spec.js
- packages/picasso.js/src/core/chart-components/axis/__tests__/axis-size-calculator.spec.js
- packages/picasso.js/src/core/chart-components/axis/axis-line-node.js
- packages/picasso.js/src/core/chart-components/axis/axis-node-builder.js
- packages/picasso.js/src/core/chart-components/axis/axis-size-calculator.js
**Checklist**
Is there a need for a flag to opt in/out of this change?
> fix: place axis line to align with other axis and and grid lines

- rollup.config.js
avoid having path pointing outside the packages as it can cause problem with overlapping paths.
> fix: adjust the source map path to hide that they are from a mono repo

- plugins/q/src/data/util.js
fixes #624 by removing the usage of the Function constructor.
Verification:
> fix: remove usage of Function constructor

- .circleci/config.yml
> chore: update api compliance

- .circleci/config.yml
Do not run API Gov check on forked pull requests.
> ci: update api gov config

- package.json
- yarn.lock
Forgot to remove protractor in #702
> chore: remove protractor as dependency

- docs/scriptappy.json
- packages/picasso.js/src/core/chart-components/text/text.js
- packages/picasso.js/types/index.d.ts
> docs: fix broken component text spec and type def

- .circleci/config.yml
- docs/package.json
- package.json
- tsconfig.json
To avoid issues like #732 , check that the generated types are valid as part of ci
> chore: add types check

- packages/picasso.js/src/core/component/component-factory.js
> fix: replace push to support adding many items into an array

- packages/picasso.js/src/core/chart/index.js
> fix: fix push(...) issue

- packages/picasso.js/src/core/data/extractor-matrix.js
- packages/picasso.js/src/web/components/brush-range/brush-area-dir.js
- plugins/q/src/data/util.js
> fix: fix push(...)

- packages/picasso.js/src/core/data/stack.js
- packages/picasso.js/src/core/data/util.js
To fix the error of maximum call stack size exceeded.
> fix: fix max, min for big array

- rollup.config.js
BREAKING CHANGE: end support for IE11
> build!: end support for IE11

- plugins/q/src/data/dataset.js
- plugins/q/src/data/field.js
for sn-treemap when not all data is fetched
**Checklist**
> feat: improve support for uneven hierarchy

- plugins/q/src/formatter/parts/qs-number-formatter.js
> fix: fix formatting issue caused by floating error

- .circleci/config.yml
> ci: use lts image

- .circleci/config.yml
- .github/workflows/unit-test.yml
> chore: use codeclimate for unit test coverage

- .circleci/config.yml
- .github/workflows/unit-test.yml
- README.md
> chore: remove unit test run circleci

- packages/picasso.js/src/web/components/tooltip/__tests__/placement.spec.js
- packages/picasso.js/src/web/components/tooltip/placement.js
> fix: adjust tooltip when it is outside

- package.json
- yarn.lock
> chore: remove coveralls

- renovate.json
Adding the dashboard to be able to manually trigger updates
> chore: renovate dashboard

- plugins/q/src/formatter/__tests__/numberFormat.spec.js
- plugins/q/src/formatter/parts/qs-number-formatter.js
To fix https://jira.qlikdev.com/browse/QB-27227
**Checklist**
> fix: fix floating error of toFixed

- package.json
- packages/picasso.js/src/core/component/interpolate-object.js
- packages/picasso.js/src/core/data/extractor-matrix.js
- plugins/q/src/data/extractor-s.js
- plugins/q/src/data/extractor-t.js
- yarn.lock
> chore: downgrade prettier to 2.8.8

- packages/picasso.js/src/core/chart-components/ref-line/__tests__/refline.spec.js
- packages/picasso.js/src/core/chart-components/ref-line/lines-and-labels.js
- packages/picasso.js/src/core/chart-components/ref-line/refline.js
Fix the negative slope line to navigate till both the end points (x1, y1) and (x2, y2) and then the oob applies.
> fix: navigating the negative slope for oob

- docs/scriptappy.json
- packages/picasso.js/src/core/chart/index.js
- packages/picasso.js/src/web/renderer/dom-renderer/__tests__/dom-renderer.spec.js
- packages/picasso.js/src/web/renderer/dom-renderer/dom-renderer.js
- packages/picasso.js/src/web/renderer/svg-renderer/__tests__/svg-renderer.spec.js
- packages/picasso.js/src/web/renderer/svg-renderer/svg-renderer.js
- packages/picasso.js/types/index.d.ts
> feat: option to hide element from screen readers
